twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    globals:
        websiteName: 'm√ºll.io'

when@test:
    twig:
        strict_variables: true
